### ISSUE TITLE
Connecting to GitHub is not possible due to invalid authorization URL

### ISSUE THREAD

**Issue by i2h3** [nextcloud/integration_github#118]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

### Steps to reproduce
1. Be signed in a Nextcloud
2. Go to user settings and connected accounts
3. Click the "Connect with GitHub" button link

### Expected behaviour

1. An authentication flow should be initiated

### Actual behaviour

1. A new browser tab is opened
2. The URL has the pattern `https://github.com/login/oauth/authorize?client_id=<redacted>&redirect_uri=<redacted>&state=<redacted>&scope=read%3Auser%20user%3Aemail%20repo%20notifications`
3. GitHub responds with "Page not found" (404, "This is not the web page you are looking for")

### Server configuration

**Web server:** _Unknown_

**Database:** _Unknown_

**PHP version:** _Unknown_

**Nextcloud version:** 30.0.2 RC1

<details>
<summary>List of activated apps</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

<details>
<summary>Nextcloud configuration</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Browser

**Browser name:** Safari

**Browser version:** 18.1 (20619.2.8.11.10)

**Operating system:** macOS Sequoia 15.1 (24B83)

<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by kyteinsky** [comment]
Hi, it seems your client ID / secret is wrong. Visit the website linked in the description in "Admin settings -> Connected accounts -> GitHub integration" to create an oauth app and enter the client ID and secret in the same settings page. Now you should be able to connect to your account.
Or, remove the client ID and secret, visit "Personal settings -> Connected accounts -> GitHub integration" and connect using personal token.

**Comment by kyteinsky** [comment]
Closing as a configuration issue.
