### ISSUE TITLE
No compatible with Firefox 68 ESR

### ISSUE THREAD

**Issue by simmstein** [nextcloud/integration_github#13]
OS: debian 10
Browser: Firefox 68 ESR

## Description

No widget to configuration the access

Firefox in the left, Vivaldi in the right

![](https://upload.deblan.org/u/2020-11/5fa135ab.png)

## Step to reproduce

Access the setting page with Firefox

## Console

![](https://upload.deblan.org/u/2020-11/5fa13510.jpg)

**Comment by eneiluj** [comment]
I couldn't find Firefox 68 ESR to try it out. It is 1.5 years old.

It works fine with latest ESR (v78).

The only reason I can think of is the usage of Javascript optional chaining which is supported by Firefox >= 74. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#Browser_compatibility

There will be many other places in Nextcloud (and in web pages in general) where you will find optional chaining (as it's freakin' convenient :grin:).

I know it's not a satisfying answer but I'll still give it: You should update your browser.

Thanks for the bug report anyway!

**Comment by eneiluj** [comment]
Btw, Firefox ESR is at v78.4.0 on Debian 10 (buster if I'm correct) : https://packages.debian.org/search?keywords=firefox-esr

**Comment by simmstein** [comment]
True, I was at the last version of 68.* and 78.4.0 has been released very recently.
Issue closed.
