### ISSUE TITLE
Feature Request: adding a link to go directly to the right place for the GitHub Token

### ISSUE THREAD

**Issue by JOduMonT** [nextcloud/integration_github#15]
It would be great if a link somewhere pointed to https://github.com/settings/tokens
such as an example, without changing anything "Personal access token" could be the link to
![image](https://user-images.githubusercontent.com/5204724/99935191-b3cd8d80-2d92-11eb-8e0c-96dae2a0a248.png)

**Comment by eneiluj** [comment]
Right, added, thanks! The link is now in the hint (only displayed when not connected).

It will be included in the next release coming soon.
