### ISSUE TITLE
Notifications dont work

### ISSUE THREAD

**Issue by axheli** [nextcloud/integration_github#18]
Not getting notifications on the app and there's new nonfictions on the GitHub the settings are all correct  

![image](https://user-images.githubusercontent.com/59488153/103366894-50b5d180-4a89-11eb-9be0-5cdff22af7d3.png)

![image](https://user-images.githubusercontent.com/59488153/103366907-57dcdf80-4a89-11eb-8273-767397425913.png)

**Comment by 19dufbri** [comment]
I'm also having this issue. I'll just add that the issue version for me is 0.0.16 on Nextcloud 20.0.4

**Comment by eneiluj** [comment]
Hi all,
Notifications are filtered to avoid having too much content in the widget. Here's what's kept:
* unread ones
* types:
    * assigned to you
    * you've been mentioned
    * your review was requested
* releases of projects you follow

Do you have one of those things in your notifications? If not, having an empty widget is expected.

**Comment by axheli** [comment]
I checked everything I first had a few things then I checked everything and still nothing

**Comment by axheli** [comment]
@eneiluj any updates on this

**Comment by eneiluj** [comment]
@axheli Do you see this comment in the widget? As I mentioned you, it should appear. If it does not appear we have a problem. I would need you to check if there are errors in the browser console or in nextcloud.log.

When I said "notifications are filtered" I meant they are filtered on the widget side.

**Comment by axheli** [comment]
@eneiluj yes I checked all my settings on the server and in github and all seem to be correct and no errors in the log regarding this.

**Comment by eneiluj** [comment]
@axheli I assume this means you don't see the 2 last comments in which I mentioned you? :grin:

If there is no error this can only mean the API is not returning the notifications you should see...

**Comment by axheli** [comment]
@eneiluj this is what i see what should i check? 
<img width="612" alt="Screen Shot 2021-01-18 at 8 24 02 AM" src="https://user-images.githubusercontent.com/59488153/104927056-9407af80-5966-11eb-9e64-7a589f35c2ea.png">

**Comment by eneiluj** [comment]
As mentioned in the "connected accounts" GitHub settings hint, you should check "read:user", "user:email" and "notifications" permissions.

That might be the issue here (hopefully).

**Comment by axheli** [comment]
Yup looks to be good. thank you
