### ISSUE TITLE
Error in GithubWidget.php

### ISSUE THREAD

**Issue by HusseinKabbout** [nextcloud/integration_github#41]
Dashboard crashes when this integration is loaded. In the logs I can see:

```
syntax error, unexpected 'IConfig' (T_STRING),
expecting function (T_FUNCTION) or const (T_CONST) in file '/PATH_TO_NEXTCLOUD/nextcloud/apps/integration_github/lib/Dashboard/GithubWidget.php' line 43
```

Probably related to https://github.com/nextcloud/integration_gitlab/issues/47

**Comment by eneiluj** [comment]
Thanks for reporting this.

It is actually a syntax which is only supported in PHP >= 7.4
Sorry for the inconvenience.

v1.0.4 is out and should work for you.
Could you try it?

**Comment by eneiluj** [comment]
Feel free to reopen if needed. Should be fixed.
