### ISSUE TITLE
ReferenceProvider is matching case sensitive

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/integration_github#51]
I just noticed that URLs are matched case sensitive only, if for example "Https" instead of "https" is used, the reference provider falls back to open graph:
<img width="585" alt="image" src="https://user-images.githubusercontent.com/1580193/194041977-f05c5d2f-5724-48a2-9a08-e1ae84ecb69c.png">

**Comment by eneiluj** [comment]
Nice catch! Thanks.
