### ISSUE TITLE
Undefined array key "title" at integration_github/lib/Reference/GithubReferenceProvider.php#111

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/integration_github#53]
From company log file:
> Undefined array key \"title\" at .../apps/integration_github/lib/Reference/GithubReferenceProvider.php#111

Request ID for further questions: 2nhP0jawTXi4Qtr9cZy6

**Comment by julien-nc** [comment]
Oops, thanks, it's fixed and will be included in the next release coming soon.
