### ISSUE TITLE
Strange code rendering

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/integration_github#61]
Just seen this in the wild:

Nothing urgent, just thought it would be nice to report :)

![Screenshot 2022-11-24 at 17 34 25](https://user-images.githubusercontent.com/3404133/203832195-6c4c51c5-3c3a-4961-9d87-3ad8eda3d937.png)

**Comment by julien-nc** [comment]
Thanks for the bug report. I started fixing this and improving error display. For your example, the GitHub API [repo content endpoint](https://docs.github.com/en/rest/repos/contents#get-repository-content) fails saying "No commit found for the ref testing". I'll have a deeper check.

**Comment by juliushaertl** [comment]
Seems to be an issue with the `/` in the branch name like `testing/direct_edit`. I don't see however how we could determine from the url what the actual ref is :/

**Comment by juliushaertl** [comment]
https://github.com/nextcloud/richdocuments/blob/testing/direct_edit/src/document.js#L27
