### ISSUE TITLE
Help configuration parameter github

### ISSUE THREAD

**Issue by Ludovicis** [nextcloud/integration_github#7]
Can you add the procedure to parameter your application, please ?
Thanks,

**Comment by eneiluj** [comment]
I'll write some documentation soon.

Could you point the things you find hard to figure out?

Brief guide:
There are 2 ways to "connect" to GitHub:
* create personal token in your settings and put it in the "linked account" (will be renamed in "connected account" soon) personal setting section
* create (on GitHub) and configure (on Nextcloud) an OAuth app in the "linked/connected account" **admin** setting section and then use the magic of OAuth by clicking on the button in "linked/connected account" **personal** setting section

**Comment by Ludovicis** [comment]
Hello eneiluj,

Personal token in my setting and linked account ok
![image](https://user-images.githubusercontent.com/16205280/93319588-56f0ac80-f810-11ea-9a41-56cb26897484.png)
![image](https://user-images.githubusercontent.com/16205280/93319649-6a037c80-f810-11ea-973a-20e5be593f2d.png)


My doubts go to the configuration oauth apps in https://github.com/settings/developers
My screen capture
![image](https://user-images.githubusercontent.com/16205280/93320383-4e4ca600-f811-11ea-86ca-b27f41786f89.png)

What is the Homepage URL and the Authorization callback URL, please ?
Actually, only searching for repositories, issue and pull request work not 
I haven't gitHub notification
I have test with https://nextcloud.domaine.org and https://nextcloud.domaine.org/auth/oauth2/callback in the Authorization callback URL in https://github.com/settings/applications/xxxxxxx, same result nothing in dashboard

Thanks for your help

**Comment by eneiluj** [comment]
Thanks for the detailed feedback!

1. OAuth app: When you create an OAuth app in GitHub, the goal is to enable all your Nextcloud users to use OAuth to authenticate to GitHub. As you are the one creating the app, put whatever you want in Homepage URL. This URL will be shown to your users when they authenticate with OAuth.

The callback URL is given to you in Nextcloud admin settings: `Make sure you set the "redirect_uri" to`...

Once you have created your OAuth app in GitHub and set the client ID and client secret in Nextcloud admin settings, you should see a new button in Nextcloud personal settings to use OAuth to authenticate to GitHub.

2. Nothing in the widget

As the search is working for you, you are successfully authenticated to GitHub. The widget should work. We might be facing a bug here. Could you look for related errors in the browser logs and in Nextcloud's server logs?

**Comment by eneiluj** [comment]
To make authentication a bit clearer:

As a Nextcloud admin you can choose to create a GitHub OAuth app **or not**.

As a Nextcloud user, if the Nextcloud admin didn't create and configure a GitHub OAuth app, you can only authenticate with a "GitHub personal token" that you create in your GitHub settings.

If a Nextcloud admin created and configured a GitHub OAuth app, then all Nextcloud users will see the "Get access with OAuth" (will be renamed in "Connect to GitHub"). The purpose of this button is to automatically get a token with OAuth. In the end, it's the same result, the Nextcloud user gets an authentication token.

**Comment by Ludovicis** [comment]
thank you for these clarifications
I have check my nextcloud log nothing, no error from your app. But always Nothing to show on dasboard...

**Comment by eneiluj** [comment]
Does the widget show "nothing to show" or does it seem like a bug?

**Comment by eneiluj** [comment]
Maybe it's just that you were not mentioned recently. Notifications are filtered to only show you the most important ones:
* things that are assigned to you
* if you were mentioned
* if your review was requested
* only show things more recent than 2 weeks

Could it be that you don't have much activity on GitHub? :grin:

**Comment by eneiluj** [comment]
@Ludovicis Let's stimulate the activity of your account :wink: .

**Comment by DavidMStraub** [comment]
Hi,

thanks for this nice integration!

It would be great if you could mention in the app store intro what the scope of the access token needs to be (which rights need to be granted).

**Comment by Proximus888** [comment]
> Your assigned has stimulate my dashboard github widget thanks 👍 
> ![image](https://user-images.githubusercontent.com/16205280/93361128-c97b7f80-f844-11ea-8f27-1d7f0a4257da.png)
> can you add in your filter, please:
> - News release
> - All conversation
> ![image](https://user-images.githubusercontent.com/16205280/93361905-abfae580-f845-11ea-832c-d0732dac43d4.png)
> 
> And in the search github nextcloud , open on new tab
> 
> Thanks again,
> 

+1

Would love a option to change/adjust the filter. What is most important for me is new releases. At the moment those notifications will never show on my dashboard widget.

Thanks for the effort!

**Comment by eneiluj** [comment]
> It would be great if you could mention in the app store intro what the scope of the access token needs to be (which rights need to be granted).

@DavidMStraub The scopes are listed in connected accounts personal settings if no OAuth configuration was done and the "personal access token" field is visible. Why would you want to see them also in the readme?

> What is most important for me is new releases

@Proximus888 I'll see what I can do. I agree new releases are important events.

About the projects you are watching, I think it's out of the widget's scope as it might generate a lot of content with "low" importance and avoid users to see what they want to focus on... Don't you think?

Making it optional is a possibility indeed but I would like to avoid adding settings/complexity.

**Comment by eneiluj** [comment]
@Proximus888 Releases are now displayed in the widget.

![release](https://user-images.githubusercontent.com/11291457/96255226-d6f86680-0fb6-11eb-87eb-48a5f3abed56.png)

This will be included in next release soon(ish).

**Comment by DavidMStraub** [comment]
> @DavidMStraub The scopes are listed in connected accounts personal settings if no OAuth configuration was done and the "personal access token" field is visible. Why would you want to see them also in the readme?

Oh really? I must have missed that somehow :thinking: But yes, that is perfectly fine then!

**Comment by eneiluj** [comment]
@Proximus888 New releases are now displayed in the widget. It's included in v0.0.7 which is out.

Let's close this swiss army knife issue :grin:.

**Comment by Proximus888** [comment]
> @Proximus888 Releases are now displayed in the widget.
> 
> ![release](https://user-images.githubusercontent.com/11291457/96255226-d6f86680-0fb6-11eb-87eb-48a5f3abed56.png)
> 
> This will be included in next release soon(ish).

Awesome, thanks
