### ISSUE TITLE
Comment section rendered on error

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/integration_github#75]
![image](https://user-images.githubusercontent.com/1580193/231720256-d37ee247-bdae-434c-8fac-39d4c309e4df.png)

Returned JSON:
![image](https://user-images.githubusercontent.com/1580193/231720388-5c1463bc-da63-4e4f-927d-e4f3daae9847.png)

I think he `v-if` at https://github.com/nextcloud/integration_github/blob/f8c43b25186d6189196e2665b588ab475ebcca18/src/views/GithubIssuePrReferenceWidget.vue#L125
needs to be adjusted and check for `isError` additionally.

**Comment by julien-nc** [comment]
Thanks for the bug report.

Fixed and included in v2.0.2 which is out.
