### ISSUE TITLE
The log gets filled with error 

### ISSUE THREAD

**Issue by teemue** [nextcloud/integration_github#79]
The log writes every second the following error:

`Creation of dynamic property OCA\\Github\\AppInfo\\Application::$container is deprecated at /var/www/html/custom_apps/integration_github/lib/AppInfo/Application.php#41`

**Comment by julien-nc** [comment]
Thanks. Could you try applying the changes of 05ab35a9739dd78d325afe599cc3b61866f6f07a and confirm the warning goes away?

**Comment by teemue** [comment]
> Thanks. Could you try applying the changes of 05ab35a9739dd78d325afe599cc3b61866f6f07a and confirm the warning goes away?

Yes, this fixes it, thanks.
